import { obsidianCopyPlugin } from "@22-2/esbuild-plugin-obsidian-copy";
import builtins from "builtin-modules";
import esbuild from "esbuild";
import path from "path";
import process from "process";


const VAULT_DIR = "E:/AppData/obsidian/vaults/suizen";
const PLUGINS_DIR = path.join(VAULT_DIR, ".obsidian/plugins");

// ---

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "esnext",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [
    obsidianCopyPlugin({
      pluginsDir: PLUGINS_DIR,
      force: true,
    }),
    obsidianCopyPlugin({
      pluginsDir: "G:/マイドライブ/documents/obsidian/vaults/sagyosen/.obsidian/plugins",
      force: true,
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
