import { obsidianCopyPlugin } from "@22-2/esbuild-plugin-obsidian-copy";
import builtins from "builtin-modules";
import esbuild from "esbuild";
import path from "path";
import process from "process";
import fs from "fs";

const VAULT_DIR = "E:/AppData/obsidian/vaults/suizen";
const PLUGINS_DIR = path.join(VAULT_DIR, ".obsidian/plugins");

// ---

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  alias: {
    "react": "preact/compat",
    "react-dom": "preact/compat",
    "react-dom/client": "preact/compat/client",
    "react-dom/test-utils": "preact/test-utils",
    "react/jsx-runtime": "preact/jsx-runtime",
  },
  format: "cjs",
  target: "esnext",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  metafile: true,
  plugins: [
    obsidianCopyPlugin({
      pluginsDir: [
        PLUGINS_DIR,
        "C:/Users/17890/AppData/Roaming/obsidian/Obsidian Sandbox/.obsidian/plugins",
        "E:/AppData/obsidian/vaults/suizen/.obsidian/plugins",
        "G:/マイドライブ/documents/obsidian/vaults/sagyosen/.obsidian/plugins",
      ],
      force: true,
    }),
  ],
});

if (prod) {
  const result = await context.rebuild();
  fs.writeFileSync("metafile.json", JSON.stringify(result.metafile));
  process.exit(0);
} else {
  await context.watch();
}
